import Head from 'next/head'

import SkillSets from '@/components/skill-sets'
import Hero from '@/components/hero'
import Projects from '@/components/project'
import Contact from '@/components/contact'
import StarsCanvas from '@/canvas/stars-canvas'

export default function Home() {
  return (
    <div className={`  overflow-y-visible overflow-x-hidden flex flex-col scroll-smooth `}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-slate-200 px-5 dark:bg-gray-900 md:px-20 lg:px-40">
        {/* hero */}
        <Hero />
        {/* Skill sets */}
        <SkillSets />
        {/* projects */}
        <Projects />
        {/* contact */}
        <div className="relative z-0" id="contact">
          <Contact />
          <StarsCanvas />
        </div>
      </main>
    </div>
  )
}
