"use client";
import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { AiOutlineCloud } from "react-icons/ai";
import { SiConsul } from "react-icons/si";
import { CgWebsite } from "react-icons/cg";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../../public/gj.png";
import code from "../../public/code.png";
import design from "../../public/design.png";
import consulting from "../../public/consulting.png";
import Image from "next/image";
import web1 from "../../public/web1.png";
import web2 from "../../public/web2.png";
import web3 from "../../public/web3.png";
import web4 from "../../public/web4.png";
import web5 from "../../public/web5.png";
import web6 from "../../public/web6.png";
import styles from "./home.module.css";
import { motion } from "framer-motion";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  const item = {
    hidden: { y: 20, opacity: 0 },
    visible: {
      y: 0,
      opacity: 1,
    },
  };

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <p className=" font-burton text-xl font-bold">
              {"</nvl>".toLowerCase()}
            </p>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <div className={` `}>
              <motion.h2
                initial={{ x: -100, opacity: 0 }}
                whileInView={{
                  opacity: 1,
                  x: 0,
                  transition: {
                    opacity: 1,

                    bounce: 0.4,
                    duration: 0.6,
                  },
                }}
                className={` ${styles.grad} text-5xl py-2 text-transparent font-medium md:text-6xl`}
              >
                Nauval Yusuf Addairy
              </motion.h2>
            </div>

            <motion.h3
              initial={{ x: 100, opacity: 0 }}
              whileInView={{
                opacity: 1,
                x: 0,
                transition: {
                  bounce: 1,
                  duration: 0.6,
                },
              }}
              className="text-2xl py-2 dark:text-white md:text-3xl"
            >
              Fullstack Developer and Certified Cloud Engineer
            </motion.h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Freelancer providing services for building web application with
              it's best architectures to run. Join me down below and let's get
              cracking!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <AiFillTwitterCircle />
              <AiFillLinkedin />
              <AiFillYoutube />
            </div>
            <div
              className={`mx-auto bg-gradient-to-b from-teal-500 ${styles.animated_border}  w-[580px] h-80 relative overflow-hidden mt-20 md:h-96 md:w-96`}
            >
              <Image alt="deved" src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance cloud engineer
              and fullstack developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including cloud
              architecture solutions with devops manner ,tech consulting, web
              design and backend development
            </p>
          </div>
          <div className=" mt-16 ">
            <h3 className="text-3xl py-1 dark:text-white ">My Skill Sets</h3>

            <motion.div
              className="md:flex gap-10
            "
            >
              {/* skill 1 */}
              <motion.div
                variants={item}
                className="text-center shadow-lg p-10 rounded-xl my-10 bg-gray-800  dark:bg-white flex flex-col items-center flex-1"
              >
                <AiOutlineCloud className="w-[100px] h-[100px] font-bold text-white dark:text-gray-800 " />
                <h3 className="text-lg font-medium pt-8 pb-2 text-white dark:text-gray-800">
                  Cloud Engineering
                </h3>
                <p
                  className="py-2 text-white/60 dark:text-gray-800/80
              "
                >
                  Build your enterprise app to be scalable, secure, always up
                  and running, even during peak traffic using cloud computing.
                  Additionally, remove unnecessary costs when your system at
                  idling state by leveraging serverless technology
                </p>
                <h4 className="py-4 text-teal-600 font-medium">
                  Technologies I Use
                </h4>
                <p className="text-white/60 dark:text-gray-800/80  py-1">
                  Amazon Web Service
                </p>
                <p className="text-white/60 dark:text-gray-800/80  py-1">
                  Firebase
                </p>
              </motion.div>
              {/* skill 2 */}
              <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-gray-800  dark:bg-white flex flex-col items-center flex-1">
                <CgWebsite className="w-[100px] h-[100px] font-bold text-white dark:text-gray-800 " />
                <h3 className="text-lg font-medium pt-8 pb-2 text-white dark:text-gray-800">
                  {" "}
                  Web Developing
                </h3>
                <p
                  className="py-2 text-white/60 dark:text-gray-800/80
              "
                >
                  Do you have a project idea? I can develop your project from
                  the front end to the back end. Let's talk !.
                </p>
                <h4 className="py-4 text-teal-600 font-medium">
                  Technologies I Use
                </h4>
                <p className="text-white/60 dark:text-gray-800/80  py-1">
                  Reactjs
                </p>
                <p className="text-white/60 dark:text-gray-800/80  py-1">
                  Nextjs
                </p>
                <p className="text-white/60 dark:text-gray-800/80  py-1">
                  Nodejs
                </p>
                <p className="text-white/60 dark:text-gray-800/80  py-1">
                  Express.js
                </p>
                <p className="text-white/60 dark:text-gray-800/80  py-1">
                  PostgreSQL
                </p>
                <p className="text-white/60 dark:text-gray-800/80  py-1">
                  MongoDB
                </p>
                <p className="text-white/60 dark:text-gray-800/80  py-1">
                  DynamoDB
                </p>
              </div>
              {/* skill 3 */}
              <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-gray-800  dark:bg-white flex flex-col items-center flex-1">
                <SiConsul className="w-[100px] h-[100px] font-bold text-white dark:text-gray-800 " />
                <h3 className="text-lg font-medium pt-8 pb-2 text-white dark:text-gray-800">
                  {" "}
                  Consulting
                </h3>
                <p
                  className="py-2 text-white/60 dark:text-gray-800/80
              "
                >
                  Are you interested in feedback for your current project? I can
                  give you tips and tricks to level it up.
                </p>
                <h4 className="py-4 text-teal-600 font-medium">
                  Communication tools I use
                </h4>
                <p className="text-white/60 dark:text-gray-800/80  py-1">
                  Google Meet
                </p>

                <p className="text-white/60 dark:text-gray-800/80  py-1">
                  Slack
                </p>
                <p className="text-white/60 dark:text-gray-800/80  py-1">
                  TeamViewer
                </p>
              </div>
            </motion.div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                alt="s"
                className=" w-full h-full rounded-lg object-cover"
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="w-full h-full rounded-lg object-cover"
                alt="w2"
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                alt="web3"
                className="h-full w-full rounded-lg object-cover"
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="w-full h-full rounded-lg object-cover"
                alt="sd"
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="w-full h-full rounded-lg object-cover"
                alt="d"
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="h-full w-full rounded-lg object-cover"
                alt="t"
                layout="responsive"
                src={web6}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
